server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tEYHju6VTNibz2e1oKy
    keySecret: mrT8e2142L20JS41IIecogtzyUF4Q3
    bucketName: srb-file-2022721